// Code generated by go wasm-bindings -package=github.com/nitram509/lib-bpmn-engine/pkg/bpmn_engine -type=BpmnEngineState; DO NOT EDIT.

package main

import "github.com/nitram509/lib-bpmn-engine/pkg/bpmn_engine"
import "syscall/js"

type BpmnEngineStateWrapper struct {
	wrapped *bpmn_engine.BpmnEngineState
}

func wrap(t bpmn_engine.BpmnEngineState) BpmnEngineStateWrapper {
	return BpmnEngineStateWrapper{
		wrapped: &t,
	}
}
func (w *BpmnEngineStateWrapper) JsGetMessageSubscriptions(this js.Value, args []js.Value) any {
	w.wrapped.GetMessageSubscriptions()
	return js.Undefined()
}

func (w *BpmnEngineStateWrapper) JsGetProcessInstances(this js.Value, args []js.Value) any {
	w.wrapped.GetProcessInstances()
	return js.Undefined()
}

func (w *BpmnEngineStateWrapper) JsGetName(this js.Value, args []js.Value) any {
	w.wrapped.GetName()
	return js.Undefined()
}
