name: update gh-pages
on:
  push:
    branches:
      - master
      - main
jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install \
          mkdocs-material \
          mkdocs-material-extensions \
          pygments \
          pymdown-extensions
      - run: mkdocs gh-deploy --force
