name: update-gh-pages
on:
  push:
    branches:
      - master
      - main
jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - name: "Compile WASM"
        run: |
          GOOS=js GOARCH=wasm go build -o static/main.wasm .
          cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" static/wasm_exec.js
      - name: "Deploy 🚀"
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: static
