name: update gh-pages
on:
  push:
    branches:
      - master
      - main
jobs:
  update-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'
      - run: |
          echo "test"
